/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalkRouteImport } from './routes/talk'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RsvpTokenRouteImport } from './routes/rsvp.$token'
import { Route as PartyIdRouteImport } from './routes/party.$id'
import { Route as PartyIdRevealRouteImport } from './routes/party.$id.reveal'
import { Route as PartyIdDayOfRouteImport } from './routes/party.$id.day-of'
import { Route as ApiRealtimeSessionRouteImport } from './routes/api/realtime/session'

const TalkRoute = TalkRouteImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpTokenRoute = RsvpTokenRouteImport.update({
  id: '/rsvp/$token',
  path: '/rsvp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyIdRoute = PartyIdRouteImport.update({
  id: '/party/$id',
  path: '/party/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyIdRevealRoute = PartyIdRevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => PartyIdRoute,
} as any)
const PartyIdDayOfRoute = PartyIdDayOfRouteImport.update({
  id: '/day-of',
  path: '/day-of',
  getParentRoute: () => PartyIdRoute,
} as any)
const ApiRealtimeSessionRoute = ApiRealtimeSessionRouteImport.update({
  id: '/api/realtime/session',
  path: '/api/realtime/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/talk': typeof TalkRoute
  '/party/$id': typeof PartyIdRouteWithChildren
  '/rsvp/$token': typeof RsvpTokenRoute
  '/api/realtime/session': typeof ApiRealtimeSessionRoute
  '/party/$id/day-of': typeof PartyIdDayOfRoute
  '/party/$id/reveal': typeof PartyIdRevealRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/talk': typeof TalkRoute
  '/party/$id': typeof PartyIdRouteWithChildren
  '/rsvp/$token': typeof RsvpTokenRoute
  '/api/realtime/session': typeof ApiRealtimeSessionRoute
  '/party/$id/day-of': typeof PartyIdDayOfRoute
  '/party/$id/reveal': typeof PartyIdRevealRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/talk': typeof TalkRoute
  '/party/$id': typeof PartyIdRouteWithChildren
  '/rsvp/$token': typeof RsvpTokenRoute
  '/api/realtime/session': typeof ApiRealtimeSessionRoute
  '/party/$id/day-of': typeof PartyIdDayOfRoute
  '/party/$id/reveal': typeof PartyIdRevealRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/talk'
    | '/party/$id'
    | '/rsvp/$token'
    | '/api/realtime/session'
    | '/party/$id/day-of'
    | '/party/$id/reveal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/talk'
    | '/party/$id'
    | '/rsvp/$token'
    | '/api/realtime/session'
    | '/party/$id/day-of'
    | '/party/$id/reveal'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/talk'
    | '/party/$id'
    | '/rsvp/$token'
    | '/api/realtime/session'
    | '/party/$id/day-of'
    | '/party/$id/reveal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  TalkRoute: typeof TalkRoute
  PartyIdRoute: typeof PartyIdRouteWithChildren
  RsvpTokenRoute: typeof RsvpTokenRoute
  ApiRealtimeSessionRoute: typeof ApiRealtimeSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talk': {
      id: '/talk'
      path: '/talk'
      fullPath: '/talk'
      preLoaderRoute: typeof TalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp/$token': {
      id: '/rsvp/$token'
      path: '/rsvp/$token'
      fullPath: '/rsvp/$token'
      preLoaderRoute: typeof RsvpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/$id': {
      id: '/party/$id'
      path: '/party/$id'
      fullPath: '/party/$id'
      preLoaderRoute: typeof PartyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/$id/reveal': {
      id: '/party/$id/reveal'
      path: '/reveal'
      fullPath: '/party/$id/reveal'
      preLoaderRoute: typeof PartyIdRevealRouteImport
      parentRoute: typeof PartyIdRoute
    }
    '/party/$id/day-of': {
      id: '/party/$id/day-of'
      path: '/day-of'
      fullPath: '/party/$id/day-of'
      preLoaderRoute: typeof PartyIdDayOfRouteImport
      parentRoute: typeof PartyIdRoute
    }
    '/api/realtime/session': {
      id: '/api/realtime/session'
      path: '/api/realtime/session'
      fullPath: '/api/realtime/session'
      preLoaderRoute: typeof ApiRealtimeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PartyIdRouteChildren {
  PartyIdDayOfRoute: typeof PartyIdDayOfRoute
  PartyIdRevealRoute: typeof PartyIdRevealRoute
}

const PartyIdRouteChildren: PartyIdRouteChildren = {
  PartyIdDayOfRoute: PartyIdDayOfRoute,
  PartyIdRevealRoute: PartyIdRevealRoute,
}

const PartyIdRouteWithChildren =
  PartyIdRoute._addFileChildren(PartyIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  TalkRoute: TalkRoute,
  PartyIdRoute: PartyIdRouteWithChildren,
  RsvpTokenRoute: RsvpTokenRoute,
  ApiRealtimeSessionRoute: ApiRealtimeSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
